baseurl:        /
asseturl:       /assets/
title:          gami's blog
sub_title:      A girl love smiling and running as well as exploring the world.
url:            https://fenggami.github.io/
timezone:       Asia/Beijing

paginate:       20
paginate_path:  '/page-:num'
markdown:       kramdown

keywords:       gami's blog
description:    gami's blog
author:
    true_name:  冯嘉美
    name:       gami
    email:      fjmbupt@163.com
