baseurl:        /
asseturl:       /assets/
title:          且听风吟技术博客
sub_title:      再也无须前思后想，一切岂非已然过往。
url:            http://blog.imzhi.me/
timezone:       Asia/Chongqing

paginate:       20
paginate_path:  '/page-:num'
markdown:       rdiscount

keywords:       且听风吟技术博客
description:    且听风吟技术博客
author:
    true_name:  杨晓智
    name:       imzhi
    email:      yxz_blue@126.com